---
- hosts: app
  sudo: true

  tasks:
  - name: Create the project directory.
    file: state=directory path=${project_root}
    
  - name: Create user.
    user: home=${project_root}/home/ name=${project_name} state=present

  - name: Project directory permissions
    file: state=directory path=${project_root} owner=${project_name} group=${project_name}    

  - name: Update the project directory.
    file: group=${project_name} owner=${project_name} mode=755 state=directory path=${project_root}
    
  - name: Create the code directory.
    file: group=${project_name} owner=${project_name} mode=755 state=directory path=${project_root}/code/

  - name: Install required system packages.
    apt: pkg=${item} state=installed update-cache=yes
    with_items: ${system_packages}

  - name: Get leiningen
    get_url: url=https://raw.github.com/technomancy/leiningen/stable/bin/lein dest=${lein_dir}
  - name: Leiningen permissions
    file: path=${lein_dir} mode=0755
    
  - name: Upload web app upstart config file
    copy: src=files/${project_name}-upstart.conf dest=/etc/init/${project_name}.conf

  - name: Upload env file
    copy: src=files/env dest=${project_root}/code/env

  - name: Make app log directory
    file: state=directory path=/var/log/${project_name} owner=${project_name} group=${project_name}
        
- hosts: database
  sudo: true

  tasks:
  - name: Create datomic user.
    user: name=datomic state=present

  - name: Create datomic data directory
    file: state=directory path=${datomic_data_dir} owner=datomic group=datomic

  - name: Make datomic log directory
    file: state=directory path=/var/log/datomic owner=datomic group=datomic
    
  - name: Check datomic installation
    command: "ls ${datomic_dir}/${datomic_filename}"
    register: datomic_exists
    ignore_errors: true

  - name: Create datomic directory
    file: state=directory path=${datomic_dir} owner=datomic group=datomic
    when: datomic_exists|failed

  - name: Download datomic
    get_url: url=http://downloads.datomic.com/${datomic_version}/${datomic_filename}.zip dest=${datomic_dir}
    when: datomic_exists|failed

  - name: Unpack datomic
    command: chdir=${datomic_dir} unzip ${datomic_filename}.zip
    when: datomic_exists|failed

  - name: datomic dir permissions
    shell: chown -R datomic:datomic ${datomic_dir}/${datomic_filename}

  - name: Upload datomic properties file
    copy: src=files/datomic-transactor.properties dest=${datomic_dir}/transactor.properties
    
  - name: Upload datomic upstart config file
    copy: src=files/datomic-upstart.conf dest=/etc/init/datomic.conf
    
  - name: Link datomic
    file: src=${datomic_dir}/${datomic_filename}
          dest=${datomic_dir}/runtime
          owner=datomic
          group=datomic
          state=link
    when: datomic_exists|failed

  - name: ensure datomic is running
    service: name=datomic state=started